#!/usr/bin/env node
import { CliTool } from './index.js'
import { cliYargs } from '@kingjs/cli-yargs'
import { hideBin } from 'yargs/helpers'

cliYargs(CliTool).then(async (yargs) => {
  // const argv = await yargs.parse('spy info @kingjs/cli-group-output'.split(' '))
  const argv = await yargs.parse(hideBin(process.argv))
  new argv._class(...argv._args)
})
