#!/usr/bin/env node
import { Clippy } from './index.js'
import { cliYargs } from '@kingjs/cli-yargs'
import { CliRuntime } from '@kingjs/cli-runtime'
import { hideBin } from 'yargs/helpers'

CliRuntime.activate(Clippy)
  .then(runtime => cliYargs(runtime.info)
    .then(async yargs => {
      const argv = await yargs.parse(hideBin(process.argv))
      // const argv = await yargs.parse('spy info spy'.split(' '))
      // const argv = await yargs.parse('poll --stdis --errorRate .2'.split(' '))
      // const argv = await yargs.parse('orb --stdin ./polling.txt'.split(' '))

      await runtime.execute(argv._, argv)
    })
  )
