#!/usr/bin/env node
import { Clippy } from './index.js'
import { cliYargs } from '@kingjs/cli-yargs'
import { hideBin } from 'yargs/helpers'

cliYargs(Clippy).then(async (yargs) => {
  // const argv = await yargs.parse('poll --stdis'.split(' '))
  const argv = await yargs.parse(hideBin(process.argv))
  await argv._class.activate(...argv._args)
})

// node.exe src\clippy\index.js poll --error-rate .5 --poll-ms 1000 --stdis | node.exe src\clippy\index.js orb
